# Generated by Django 2.1.5 on 2019-01-20 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyid', models.AutoField(primary_key=True, serialize=False)),
                ('facultyname', models.CharField(max_length=100)),
                ('facultymobileno', models.IntegerField()),
                ('facultyemail', models.EmailField(max_length=254)),
                ('facultysalary', models.IntegerField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Courses')),
            ],
        ),
    ]
