# Generated by Django 2.0.6 on 2019-01-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parentid', models.AutoField(primary_key=True, serialize=False)),
                ('parentname', models.CharField(max_length=20)),
                ('pusername', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=6)),
                ('sdn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.Department')),
                ('srn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student')),
            ],
        ),
    ]
