# Generated by Django 2.1.5 on 2019-01-14 09:55

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('courseduration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=100)),
                ('deptlocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyid', models.AutoField(primary_key=True, serialize=False)),
                ('facultyname', models.CharField(max_length=100)),
                ('facultymobileno', models.IntegerField()),
                ('facultyemail', models.EmailField(max_length=254)),
                ('facultysalary', models.IntegerField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.IntegerField()),
                ('parentname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semid', models.IntegerField()),
                ('semdetails', models.CharField(max_length=20)),
                ('semduration', models.IntegerField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('studname', models.CharField(max_length=50)),
                ('studaddress', models.CharField(max_length=100)),
                ('studmobileno', models.IntegerField()),
                ('studemail', models.EmailField(max_length=254)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Courses')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Department')),
                ('semid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subcode', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('subname', models.CharField(max_length=10)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Courses')),
                ('semid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Faculty')),
                ('subcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Subject'),
        ),
        migrations.AddField(
            model_name='parent',
            name='prn',
            field=compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Student', to_fields={'did': compositefk.fields.LocalFieldValue('sdn'), 'rollno': compositefk.fields.LocalFieldValue('srn')}),
        ),
        migrations.AddField(
            model_name='parent',
            name='sdn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Department'),
        ),
        migrations.AddField(
            model_name='parent',
            name='srn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ParentStudRollNo', to='CMSApp.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('rollno', 'did')},
        ),
    ]
