# Generated by Django 2.1.5 on 2019-01-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('courseduration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=100)),
                ('deptlocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyid', models.AutoField(primary_key=True, serialize=False)),
                ('facultyname', models.CharField(max_length=100)),
                ('facultymobileno', models.IntegerField()),
                ('facultyemail', models.EmailField(max_length=254)),
                ('facultysalary', models.IntegerField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semid', models.IntegerField()),
                ('semdetails', models.CharField(max_length=20)),
                ('semduration', models.IntegerField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('studname', models.CharField(max_length=50)),
                ('studaddress', models.CharField(max_length=100)),
                ('studmobileno', models.IntegerField()),
                ('studemail', models.EmailField(max_length=254)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Courses')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Department')),
                ('semid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.CharField(max_length=6)),
                ('subname', models.CharField(max_length=10)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Courses')),
                ('facultyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Faculty')),
                ('semid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Subject'),
        ),
        migrations.AddField(
            model_name='semester',
            name='subcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Subject'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.Student'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='subcode',
            field=models.ManyToManyField(blank=True, to='CMSApp.Subject'),
        ),
    ]
