# Generated by Django 2.0.6 on 2019-01-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0001_initial'),
        ('Subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.Faculty')),
                ('subcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subject.Subject')),
            ],
        ),
    ]
