# Generated by Django 2.1.5 on 2019-02-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userType', models.CharField(max_length=1)),
                ('urlFormat', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Data', models.CharField(max_length=200)),
                ('updatedData', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
