# Generated by Django 2.0.6 on 2019-01-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='facultyaddress',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
