# Generated by Django 2.1.5 on 2019-02-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=100)),
                ('deptlocation', models.CharField(max_length=100)),
            ],
        ),
    ]
